### ISSUE TITLE
HttpHeaders: need case insensitive get, set, and put

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#104]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on May 05, 2012 11:07:17_

External references, such as a standards document, or specification? http://javadoc.google-http-java-client.googlecode.com/hg/1.8.3-beta/com/google/api/client/http/HttpHeaders.html Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? All Please describe the feature requested. Unlike JSON and URL parameters, HTTP headers are case insensitive.  However, the get, put, and set methods from GenericData are case sensitive.  For example, here is an issue reported from a user:

httpRequest.getHeaders().setAccept("_/_");
httpRequest.getHeaders().set("accept", "text/plain");
httpRequest.execute();

java.lang.IllegalArgumentException: multiple headers of the same name (headers are case insensitive): accept
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:115)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:750)

There are three ways I can think of that we could potentially deal with that:
1. Override get, set, and put in HttpHeaders to be case insensitive, OR
2. Add getCaseInsensitive, setCaseInsensitive, and putCaseInsensitive to GenericData to provide this functionality, OR
3. Force all HTTP headers to be lower case, and always toLowerCase() the HTTP header name in get, set, and put, perhaps adding a caseInsensitive parameter to GenericData to alter how it works internally for this case

Note that a case insensitive implementation for options 1 and 2 is generally slower than a case sensitive implementation because we have to iterate over all headers.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=104_

**Comment by jbower1950** [comment]
v1.2.3-alpha (latest for google-api-client-util on maven central - https://mvnrepository.com/artifact/com.google.api.client/google-api-client-util) includes com.google.api.client.util.GenericData which does not contain FLAGS nor carry out the need for FLAGS from your 9-Jan-2015 posting.

This results in the following when import com.google.api.client.http.HttpHeaders; (extended GenericData) is used during Google http login process:

java.lang.NoSuchMethodError: com.google.api.client.util.GenericData.<init>(Ljava/util/EnumSet;)V
	at com.google.api.client.http.HttpHeaders.<init>(HttpHeaders.java:61)

All builds are labeled "alpha". Can someone make an effort to bring them in line with the rest of the api?
