### ISSUE TITLE
Support content of type multipart/form-data

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#107]
_From [titogar...@gmail.com](https://code.google.com/u/103517264625225210798/) on May 09, 2012 04:41:04_

External references, such as a standards document, or specification? multipart/form-data: http://tools.ietf.org/html/rfc2388 Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? All Please describe the feature requested. Add MultipartFormDataContent to the set of HttpContent classes.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=107_

**Comment by jamesdlow** [comment]
The attachments didn't import from code.google.com when this issue was imported. You can find Marco's original MultipartFormDataContent.java here:

https://github.com/marcosalis/kraken/blob/master/src/com/google/api/client/http/MultipartFormDataContent.java

**Comment by marko-p** [comment]
Thanks for the MultipartFormDataContent.java, it saved my day! :)
