### ISSUE TITLE
Where can i download the .jar? (i don't want to compile every lib i download from github by myself)

### ISSUE THREAD

**Issue by jayjupdhig** [googleapis/google-http-java-client#1110]
Where can i download the .jar? (i don't want to compile every lib i download from github by myself)

**Comment by chingor13** [comment]
This library is published to Maven Central: https://search.maven.org/artifact/com.google.http-client/google-http-client

We strongly suggest using a build tool like Maven or Gradle to fetching/resolve/download your dependencies rather than using jars directly.

**Comment by jayjupdhig** [comment]
thx
