### ISSUE TITLE
Define HTTP Version?

### ISSUE THREAD

**Issue by jayjupdhig** [googleapis/google-http-java-client#1117]
Hi there

How can i set the HTTP version that the Google HTTP Client should use? Thank you for your feedbacks.

Kind regards,
Jan

**Comment by jayjupdhig** [comment]
is that possible or not??

Thank you for your feedbacks.

**Comment by chingor13** [comment]
Do you mean the HTTP protocol version? Like 1.1 vs 1.0? There is not a way to configure that - the provided transports currently use HTTP 1.1.

**Comment by jayjupdhig** [comment]
ok thx

**Comment by jayjupdhig** [comment]
solved now???
