### ISSUE TITLE
Support for Android 4.1+

### ISSUE THREAD

**Issue by DjToMeK27** [googleapis/google-http-java-client#1241]
Hello!

I wanted to use this library for use in Speech-to-Text-API on Android 4.1 with Google cloud.
I fixed TLS 1.2 problem with using that library on older devices, and the biggest problem here it was that you are using for example StandardCharsets.UTF_8 for encoding types and this functions are not supported on Android 4.1(SDK 16), and can only be used on Android 4.4(SDK 19+).
Why did you go for this I don't know, but the same can be accomplished with using Charset library, like Charset.forName("UTF-8").

So I had to manually change all StandardCharset imports to Charset ones in this files (and I had deleted 1 test) in 
https://imgur.com/a/iU7yjCZ

And when I build this, everything works great using Android 4.1 and I can support older devices! I also created a new github project with few of this googleapis compiled into jar https://github.com/DjToMeK27/CloudGoogleSpeechToText

I know that you probably don't care about older devices (or me :) ), but some of us are still using them and something like this can greatly improve our life in building your libraries.
So if you can, please change it, because there is no difference in functionality in using one or the other.

Thank you!

**Comment by elharo** [comment]
You are correct. The minimum supported android version is 4.4.
