### ISSUE TITLE
Broken fasterxml javadoc links

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#1278]
@lesv

**Comment by eaball35** [comment]
Not sure if related but these links are broken at 432 and 433. 

https://maven.apache.org/plugins/maven-javadoc-plugin/examples/links-configuration.html
* all given links should have a fetchable /package-list file

**Comment by eaball35** [comment]
This repo also doesn't use java-shared-config where the newer [changes](https://github.com/googleapis/java-shared-config/pull/213/files) were made but does include the [publish_javadoc11](https://github.com/googleapis/google-http-java-client/tree/master/.kokoro/release) kokoro release job

**Comment by eaball35** [comment]
@elharo Can you provide any more context or an example of where you're seeing this issue? Thanks!

**Comment by elharo** [comment]
#1275 fixed this, I think.
