### ISSUE TITLE
HttpRequest should not log the Authorization-header in batched requests

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#129]
_From [mlin...@google.com](https://code.google.com/u/109832679690262212511/) on June 15, 2012 08:22:51_

Version of google-http-java-client (e.g. 1.5.0-beta)? \* Describe the problem. Currently the Authorization header will be logged in every batched request, even if the logging level is set to CONFIG, as the content of the batch request is logged as a single piece. 
We should support suppressing the Authorization header in logged requests for batch as we do have for normal ones. How would you expect it to be fixed? Create a BatchedLowLevelHttpRequest and remove the Writer parameter from HttpHeaders.addHeader, and set the logger variable to the actual logger.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=129_

**Comment by sduskis** [comment]
@ajaaym, can you please ask someone to look at this?

**Comment by ajaaym** [comment]
@wonderfly this seems already [fixed](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java#L871) Closing this for now. Please reopen if this is still an issue.
