### ISSUE TITLE
Mandatory dependence to javax.annotation in osgi environment

### ISSUE THREAD

**Issue by amergey** [googleapis/google-http-java-client#1323]
#### Environment details
OS:Linux
Java version:1.8
google-http-java-client version: 1.39.1

#### Any additional information below
osgi manifest requires javax.annotation, which makes jsr305 bundle mandatory at runtime (in osgi)

Import-Package: com.google.common.base;version="[30.1,31)",com.google.
 common.collect;version="[30.1,31)",com.google.common.io;version="[30.
 1,31)",com.google.common.util.concurrent;version="[30.1,31)",io.openc
 ensus.common,io.opencensus.contrib.http.util,io.opencensus.trace,io.o
 pencensus.trace.export,io.opencensus.trace.propagation,**javax.annotati
 on;version="[3.0,4)"**,javax.net.ssl,org.apache.http,org.apache.http.cl
 ient,org.apache.http.client.methods,org.apache.http.conn,org.apache.h
 ttp.conn.params,org.apache.http.conn.routing,org.apache.http.conn.sch
 eme,org.apache.http.conn.ssl,org.apache.http.entity,org.apache.http.i
 mpl.client,org.apache.http.impl.conn,org.apache.http.impl.conn.tsccm,
 org.apache.http.message,org.apache.http.params,org.apache.http.protoc
 ol

javax.annotation should not be mandatory at runtime

**Comment by danthe1st** [comment]
Adding `;resolution=optional` should fix the problem.
