### ISSUE TITLE
GoogleApis: Use of ApachetHttpTransport behind a proxy produces NonRepeatableRequestException

### ISSUE THREAD

**Issue by ivanjr-bb** [googleapis/google-http-java-client#1398]
#### Environment details
- Java 8
- google-http-client versions:
  - google-http-client-apache-v2-1.30.1
    - google-http-client-1.30.1	
  - google-api-client-1.30.2
    - google-http-client-jackson2-1.30.1		
    - google-oauth-client-1.30.1

#### Steps to reproduce

1. Trying to make a POST request behind a proxy produces a NonRepeatableRequestException.
2. It seems like ApacheHttpRequest wraps ByteArrayContent that is repeatable ([JavaDoc](https://googleapis.dev/java/google-http-client/latest/com/google/api/client/http/ByteArrayContent.html)) inside a ContentEntity that is non-repeatable.
3. Debuging execution, first proxy is returning "407 Proxy Authentication Required", then it tries to repeat the request (guess that including the credentials) and that exception arises because ContentEntity used is non-repeatable.

![image](https://user-images.githubusercontent.com/78910474/122387639-59369180-cf6f-11eb-8be7-174885cbd0e7.png)

#### Code example

```java
// 1.- Setting ssl and proxy
HttpClientBuilder builder = HttpClientBuilder.create();
            
SSLContext sslContext = SslUtils.getTlsSslContext();
SslUtils.initSslContext(sslContext, GoogleUtils.getCertificateTrustStore(), SslUtils.getPkixTrustManagerFactory());
builder.setSSLSocketFactory(new SSLConnectionSocketFactory(sslContext));
            
builder.setProxy(new HttpHost(host, port));
CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
credentialsProvider.setCredentials(new AuthScope(host, port), new UsernamePasswordCredentials(user, pass));
builder.setDefaultCredentialsProvider(credentialsProvider);

// 2.- Build request
HttpTransport httpTransport = new ApacheHttpTransport(builder.build());
HttpRequestFactory factory = httpTransport.createRequestFactory(credential);

HttpContent httpContent = new ByteArrayContent("application/json", "{}")
HttpRequest request = factory.buildRequest("POST", new GenericUrl(url), httpContent);

// 3.- Execute request
HttpResponse httpResponse = request.execute();
```

#### Stack trace
```
org.apache.http.client.ClientProtocolException
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar!/:4.5.13]
    at com.google.api.client.http.apache.v2.ApacheHttpRequest.execute(ApacheHttpRequest.java:73) ~[google-http-client-apache-v2-1.39.2.jar!/:?]
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[google-http-client-1.39.2.jar!/:1.39.2]
    at 
    ...
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity.
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:225) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar!/:4.5.13]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar!/:4.5.13]
    at com.google.api.client.http.apache.v2.ApacheHttpRequest.execute(ApacheHttpRequest.java:73) ~[google-http-client-apache-v2-1.39.2.jar!/:?]
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[google-http-client-1.39.2.jar!/:1.39.2]

```

**Comment by ivanjr-bb** [comment]
Asked as question in SO: https://stackoverflow.com/questions/68002387/using-google-http-client-and-google-http-client-apache-v2-behind-a-proxy-produce

**Comment by ivanjr-bb** [comment]
As workaround what I'm trying is to wrap **ApacheHttpTransport** in **CustomApacheHttpTransport**, which delegate the result of methods to **ApacheHttpTransport** except for **_buildRequest_** method.

This **_buildRequest_** method in **CustomApacheHttpTransport** builds a custom request of type **CustomApacheHttpRequest**.
```
public final class CustomApacheHttpTransport extends HttpTransport {
	
	private ApacheHttpTransport apacheHttpTransport;
	
	public CustomApacheHttpTransport (HttpClient httpClient) {
		this.apacheHttpTransport = new ApacheHttpTransport(httpClient);
	}
	
	@Override
	protected LowLevelHttpRequest buildRequest (String method, String url) {
		HttpRequestBase requestBase;
		if (method.equals("DELETE")) {
			requestBase = new HttpDelete(url);
		} else if (method.equals("GET")) {
			requestBase = new HttpGet(url);
		} else if (method.equals("HEAD")) {
			requestBase = new HttpHead(url);
		} else if (method.equals("PATCH")) {
			requestBase = new HttpPatch(url);
		} else if (method.equals("POST")) {
			..
		}
		return new CustomApacheHttpRequest(apacheHttpTransport.getHttpClient(), requestBase);
	}
}
```

This custom request is like **ApacheHttpRequest** except for when it is executed it creates a custom entity, **CustomContentEntity**, which will be repeatable depending on whether the request content supports retries.

```
final class CustomApacheHttpRequest extends LowLevelHttpRequest {
	
	private final HttpClient httpClient;
	private final HttpRequestBase request;
	private RequestConfig.Builder requestConfig;
	
	CustomApacheHttpRequest (HttpClient httpClient, HttpRequestBase request) {
		this.httpClient = httpClient;
		this.request = request;
		this.requestConfig = RequestConfig.custom().setRedirectsEnabled(false).setNormalizeUri(false).setStaleConnectionCheckEnabled(false);
	}
	
	...
		
	@Override
	public LowLevelHttpResponse execute () throws IOException {
		if (this.getStreamingContent() != null) {
			Preconditions.checkState(request instanceof HttpEntityEnclosingRequest, "Apache HTTP client does not support %s requests with content.", request.getRequestLine().getMethod());
			
			CustomContentEntity entity = new CustomContentEntity(this.getContentLength(), this.getStreamingContent());
			entity.setContentEncoding(this.getContentEncoding());
			entity.setContentType(this.getContentType());
			if (this.getContentLength() == -1L) {
				entity.setChunked(true);
			}
			((HttpEntityEnclosingRequest) request).setEntity(entity);
		}
		
		request.setConfig(requestConfig.build());
		return new CustomApacheHttpResponse(request, httpClient.execute(request));
	}
}
```

The key in **CustomContentEntity** is **_isRepeatable_** method wich do not returns always **false** as **ContentEntity** does.
```
final class CustomContentEntity extends AbstractHttpEntity {
	
	private final long contentLength;
	private final StreamingContent streamingContent;
	
	CustomContentEntity (long contentLength, StreamingContent streamingContent) {
		this.contentLength = contentLength;
		this.streamingContent = streamingContent;
	}
	
	@Override
	public boolean isRepeatable () {
		return ((HttpContent) streamingContent).retrySupported();
	}
	...
}
```

Also I have to create **CustomApacheHttpResponse** as response for **CustomApacheHttpRequest** because **ApacheHttpRequestProxy** is package-private (**CustomApacheHttpResponse** is exactly like **ApacheHttpResponse**).

**Comment by chanseokoh** [comment]
@ivanjr-bb can you check if the latest version (1.40.0 as of now) has the same issue?

**Comment by ivanjr-bb** [comment]
I tried with this set of libraries getting the same error:

- google-api-client-1.31.5:
  - google-http-client-jackson2-1.39.2 (add explicitly)
  - google-oauth-client-1.31.5
  - google-http-client-apache-v2-1.39.2
 
When I tried, google-api-client-1.31.5 was the latest version:
![image](https://user-images.githubusercontent.com/78910474/136330461-131e7b76-dac0-4dcc-b924-c13e172b7919.png)

**Comment by chanseokoh** [comment]
Sorry, forgot this one.

This is working as intended. POST requests are fundamentally considered non-retryable, as they are most likely to [have the server store data](https://en.wikipedia.org/wiki/POST_(HTTP)) and a server is recommended to [return 201 (Created) as a response](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.3). Retrying a POST request may end up inserting, uploading, or posting data multiple times. This is why sometimes web browsers show the following prompt to avoid "a duplicate transaction":

![image](https://user-images.githubusercontent.com/10523105/142929079-c06c480c-5e93-4957-9759-8024101ca3c6.png)

A potential retry logic for POST should be at the user application level, not at the library level.

In your case, the cause of the error is that you are not authorized to use the proxy. Therefore, you need to authenticate with the proxy first before attempting to use it, and then send (or re-send) a POST request.

**Comment by ivanjr-bb** [comment]
I do not agree with the answer. I'm including the credentials to use the proxy in the following lines of my example:

```
...           
builder.setProxy(new HttpHost(host, port));
CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
credentialsProvider.setCredentials(new AuthScope(host, port), new UsernamePasswordCredentials(user, pass));
builder.setDefaultCredentialsProvider(credentialsProvider);
...
```

If as you say I'm not authorized to use the proxy:
- Why is the library who tries to repeat the request? (failling on a POST request).
- Why the library have the same behaviour (retrying the request) with a GET request?  (but in this case sucessfully because GET request do not have entity and do not matters if it is repeatable or not).
- Why if I change the entity, as show in workaround, to make it repeatable, the POST request works successfully through the proxy for which you say I'm not authorized to use?

Thanks in advance.

**Comment by ivanjr-bb** [comment]
I'm not programed my app to repeat the request, who repeat the request is Apache HttpClient (see `while(true)` at MainClientExec). Where RequestEntityProxy (HttpClient) is repeatable (consumed = false) and wraps ContentEntity (google-http-client-apache-v2):

![image](https://user-images.githubusercontent.com/78910474/143223808-52ce1d30-5027-4753-938d-20bdbb794db5.png)

![image](https://user-images.githubusercontent.com/78910474/143224968-5dbd24a5-b139-4c0c-959f-8b79a56fcfcb.png)

Getting `407 Proxy Authentication Required` (despite include the credentials) and RequestEntityProxy (HttpClient) becomes non-repeatable (consumed = true):

![image](https://user-images.githubusercontent.com/78910474/143225085-7b536491-ecaf-42ed-afb9-f5334eacdd19.png)

![image](https://user-images.githubusercontent.com/78910474/143225355-102ba933-fe1d-4b63-ab64-57b0cf876992.png)

Then because entity is not repeatable MainClientExec throws commented exception:

![image](https://user-images.githubusercontent.com/78910474/143225941-206d5acb-1974-4457-b96d-68e269bd8b5d.png)

**Comment by chanseokoh** [comment]
> who repeat the request is Apache HttpClient

Yes, of course. Now I see what you are missing and where you have a wrong idea. When interacting with a proxy (or a non-proxy) that requires auth, generally you (whether it is you or the Apache library) will **have to make at least TWO requests**. First, you try without sending any senestive information (why would you disclose your information upfront to someone who cannot be trusted? Even if you trust them, you don't really know if they are going to need your info at all). That request may fail with an error like "407 Proxy Authentication Required" (people call this that the server is "challenging" you), and **based on what the server says**, you will need to take the right action to prepare an auth header for the **second request.** And the Apache library does that for you.

>  (despite include the credentials)

What would you expect that calling `.setCredentialsProvider` would do? It doesn't do what you are currently thinking. As I said earlier, in the end, you need to provide the right form of credentials that the server expect after checking the value of `Proxy-Authenticate`, which tells you how you should **correctly** auth with the server. That is why generally you **have to repeat** a request. If all these sound ailen, please take a moment to read [this doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) to understand how this challenge-based HTTP auth framework works.

**Comment by ivanjr-bb** [comment]
Back on this topic.

Now I think I understand your arguments. If I have understood correctly, what is wrong with my approach is letting Apache library do retries when `407 Proxy Authentication Required` is obtained instead of configure Apache library not to do that and manage it manually from client.

Thanks for instructive explanation.
