### ISSUE TITLE
Make OpenCensus dependency optional

### ISSUE THREAD

**Issue by abaker** [googleapis/google-http-java-client#1424]
Exodus started flagging OpenCensus in their list of trackers. [Here](https://reports.exodus-privacy.eu.org/en/reports/167485/) is an example report for my open source Android app.

It was mentioned [here](https://github.com/googleapis/google-http-java-client/pull/837#issuecomment-541164657) that this dependency could be optional. I'm going to start getting complaints about trackers from F-Droid users so it would be great if this happened. Thanks!

**Comment by Neenu1995** [comment]
Hi,

Since opensensus does not do anything without being explicitly called upon, it has been decided that making it optional will be more inconvenient breaking change for customers who are already using it.
