### ISSUE TITLE
SocketTimeoutException: Read timed out when executing HTTPS requests

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#146]
_From [ma...@onlulu.com](https://code.google.com/u/106041519528037884424/) on July 31, 2012 09:43:21_

Version of google-http-java-client (e.g. 1.5.0-beta)? 1.10.3 Beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Android 4.1 (Google Nexus) Describe the problem. I'm using an HttpTransport got with AndroidHttp.newCompatibleTransport() to perform multiple requests to a server using the HTTPS protocol. Both using WiFi and 3G, I sometimes get this exception when executing a request:

07-31 17:14:40.659: W/System.err(7558): java.net.SocketTimeoutException: Read timed out
07-31 17:14:40.659: W/System.err(7558):     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
07-31 17:14:40.659: W/System.err(7558):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:675)
07-31 17:14:40.659: W/System.err(7558):     at libcore.io.Streams.readSingleByte(Streams.java:41)
07-31 17:14:40.659: W/System.err(7558):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:659)
07-31 17:14:40.659: W/System.err(7558):     at libcore.io.Streams.readAsciiLine(Streams.java:201)
07-31 17:14:40.659: W/System.err(7558):     at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
07-31 17:14:40.659: W/System.err(7558):     at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
07-31 17:14:40.659: W/System.err(7558):     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
07-31 17:14:40.659: W/System.err(7558):     at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
07-31 17:14:40.659: W/System.err(7558):     at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
07-31 17:14:40.659: W/System.err(7558):     at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
07-31 17:14:40.667: W/System.err(7558):     at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:91)
07-31 17:14:40.667: W/System.err(7558):     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:895)

Note that:
- Other HTTP requests complete normally in the meantime.
- My connection and read timeouts are set respectively to 10 and 20 seconds.

There are other users experiencing this issue with the error reporting library ACRA, which might use google-http-java-client as well. This is the link to the issue: https://code.google.com/p/acra/issues/detail?id=128 How would you expect it to be fixed? No idea, I don't even know if it's a library or system issue.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=146_

**Comment by msangel** [comment]
So if we will use google-http-java-client  sameversion as Android 7.1(or above) , in our projects, then we will be free of this bug?

**Comment by notdang** [comment]
I am seeing something similar, can someone else check the certificates and let me know if those certificates are also issued by Letsencrypt ?

**Comment by jackyq2015** [comment]
Any fix for this? 

I am using Linux 18.0.4 and Java 8. have the same issue, 20 seconds timeout for read a sheet. Seems the way suggested by google is not working:
```
            public void initialize(HttpRequest httpRequest) throws IOException {
                credential.initialize(httpRequest);
                httpRequest.setConnectTimeout(3 * 60000);  // 3 minutes connect timeout
                httpRequest.setReadTimeout(3 * 60000);  // 3 minutes read timeout
            }
```

**Comment by thehesiod** [comment]
we just started seeing large consistent socket read timeouts with the python client with a timeout of 15s.  Interestingly this was prefixed with rate limiter errors.  I'm wondering if they're banning IPs?
