### ISSUE TITLE
Google Cloud Hosting Platform databases system Admin 

### ISSUE THREAD

**Issue by 1989shack** [googleapis/google-http-java-client#1696]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
What the problem is. Example: I'm always frustrated when [...]

**Describe the solution you'd like**
What you want to happen.

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Additional context**
Any other context or screenshots about the feature request.

**Comment by blakeli0** [comment]
Closing for now, please provide more info if there is an issue.
