### ISSUE TITLE
Java 7 test

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-http-java-client#1713]
This change https://github.com/googleapis/google-http-java-client/commit/f0c0488a961d40781eb44a006da101bf95dd22d9 seems to have removed Java 7 tests.

**Comment by alicejli** [comment]
@suztomo I thought Java 7 was no longer officially supported after July this year, per https://cloud.google.com/java/docs/supported-java-versions?

**Comment by lqiu96** [comment]
@suztomo Bumping thread. 

Agree with @alicejli. Do we need to keep Java 7 support for this library?

![image](https://user-images.githubusercontent.com/6621793/189922009-c16642c7-2c08-426f-95a5-750fb906e83b.png)

**Comment by suztomo** [comment]
For Android compatibility of Apiary, this repository targets Java 7 https://github.com/googleapis/google-http-java-client/blob/main/pom.xml#L282

**Comment by lqiu96** [comment]
Ah, makes sense. I'll revisit https://github.com/googleapis/google-http-java-client/pull/1714 then
