### ISSUE TITLE
TrustAllX509TrustManager Android lint error

### ISSUE THREAD

**Issue by kackogut** [googleapis/google-http-java-client#1794]
#### Environment details

```
Android Studio Dolphin | 2021.3.1 Patch 1
Library version: v1.42.3
```

#### Steps to reproduce

  1. Create new Android project
  2. Add dependency for Google Http client: `implementation("com.google.http-client:google-http-client:1.42.3")`
  3. Run `lintDebug`

#### Stack trace
```
com/google/api/client/util/SslUtils$1.class: Error: checkServerTrusted is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers [TrustAllX509TrustManager]

   Explanation for issues of type "TrustAllX509TrustManager":
   This check looks for X509TrustManager implementations whose
   checkServerTrusted or checkClientTrusted methods do nothing (thus trusting
   any certificate chain) which could result in insecure network traffic
   caused by trusting arbitrary TLS/SSL certificates presented by peers.
```

**Comment by diegomarquezp** [comment]
Hi Kacper, thanks for reporting this. 
It's possible to ignore or reduce the severity of this warning (see [TrustAllX509TrustManager - suppress section](https://googlesamples.github.io/android-custom-lint-rules/checks/TrustAllX509TrustManager.md.html)) . Maybe a [custom lint file](https://googlesamples.github.io/android-custom-lint-rules/usage/lintxml.md.html) may help with your use case.
Also, please keep in mind that for faster response times you can refer to our [Customer Support Hub](https://cloud.google.com/support-hub) if you have a support contract.

**Comment by diegomarquezp** [comment]
Closing as solved.
