### ISSUE TITLE
Get parse HttpResponse content twice

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#192]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on January 14, 2013 08:26:44_

See original request: https://code.google.com/p/google-api-java-client/issues/detail?id=542 copied here:

Reported by jor...@uber.com, Jun 26, 2012
Version of google-api-java-client (e.g. 1.5.0-beta)?
ALL

Java environment (e.g. Java 6, Android 2.3, App Engine)?
Android

When using parseAsString on HttpResponse, it consumes the InputStream. It is then unusable with the parseAs method. I want to be able to get a string for my own logs (and I don't want to use the provided HttpTransport.LOGGER) and then be able to parseAs().

How would you expect it to be fixed?

HttpResponse could have a method writeTo(OutputStream os) so that we can get the content. This method would have to make sure the stream can be re-read.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=192_

**Comment by winstonma** [comment]
Hi I also want to read the content twice (parseAs and parseAsString for calculating MD5).

**Comment by ajaaym** [comment]
HttpResponse has getContent which returns the stream. Better to get stream and manage it on application side. Closing this issue for now. Please reopen if need further guidance.
