### ISSUE TITLE
Dependency: DOS issue reported by Snyk with outdated jackson-core version 2.14.2

### ISSUE THREAD

**Issue by elevenfive** [googleapis/google-http-java-client#1966]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-http-java-client/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: N/A
3. Java version: N/A
4.  version(s):  1.44.2 (current a/o 2024-06-26) and earlier

#### Steps to reproduce

  1. N/A - pom is out of date

#### Code example

N/A

#### Stack trace

N/A

#### External references such as API reference guides

https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538

#### Any additional information below

N/A

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by ldetmer** [comment]
Thanks! The latest release (1.45.0) has jackson upgraded to 2.17.2
