### ISSUE TITLE
EOF Exception Android API 14+ ,  URLConnection

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#213]
_From [chris.mark.jenkins@gmail.com](https://code.google.com/u/chris.mark.jenkins@gmail.com/) on March 27, 2013 08:55:20_

Version of google-http-java-client (e.g. 1.5.0-beta)? 1.13.1-beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Java 6, Android 4.X (Galaxy Nexus, Nexus 4, Nexus 7, Samsung S2) (Real devices NOT AVD). Describe the problem. Connection spoiling the header by leaving an old connection open. See attached forum post: https://groups.google.com/forum/?fromgroups=#!topic/android-developers/e_FExl6jl90 This is a sporadic bug, but "looks" like the connection terminated the connection randomly when it appears that the old connection is not "cleaned" properly. How would you expect it to be fixed? As mentioned in the forum post I am fixing the request with the following method when creating the request.

``` java
public static void tryToFixNetHttpRequest(final HttpHeaders headers)
{
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.ICE_CREAM_SANDWICH)
            try
            {
                headers.set("Connection", "close");
            }
            catch (Exception e)
            {
            }
}
```

So far I am yet to see the error again. We can of course use this as a work around on android, but a better solution would be more appropriate.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=213_

**Comment by rayvo** [comment]
I got my code works only on my local machine 192.168..X.X:8080 Tomcat Server.
But when I run this code on a real server with a public IP X.X.X.X:80...I got this error.

I tried your solution with "http.maxConnections" will send a file with maxconnections number to the server.....and still cannot solve the problem. ALTHOUGH ERROR IS STILL THERE.

Any suggestion? 
Thanks

**Comment by jamalis** [comment]
Gee thanks a lot, with the post above I became rather well-informed about the discussions.
http://fotorumahmewah.com

**Comment by soulfly** [comment]
The fix with **setRequestProperty("Connection", "close")** should work, but I have a question: it means that we can't use **Connection: keep-alive**, so every new request will be a new connection to server?

**Comment by vaughandroid** [comment]
Over a year and no movement on this? 👎

**Comment by sduskis** [comment]
This issue is super old.  I'm going to close this. If someone comes along, and sees this, please open a new issue.
