### ISSUE TITLE
UTF-8 encoding isn't assumed for application/json unless charset=utf-8 is also present

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#221]
_From [steve.s...@ziconix.com](https://code.google.com/u/114667561305234350101/) on May 11, 2013 09:19:43_

Version of google-http-java-client (e.g. 1.15.0-rc)? 1.14-beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Android 4.0.4 Describe the problem. A Django/Tastypie server returns only "Content-Type: application/json" with no charset parameter at the end. According to the bug report, they believe that this is correct as per RFC4627 (JSON) ( https://github.com/toastdriven/django-tastypie/issues/717 ). 

Within google-http-java-client, HttpResponse.getContentCharset() assumes an ISO-8859-1 encoding where there is no charset parameter within the returned Content-Type field. For "application/json" it should in fact assume the UTF-8 encoding that is the default according to http://www.ietf.org/rfc/rfc4627.txt How would you expect it to be fixed? If the mime type and subtype are application and json respectively, then HttpResponse.getContentCharset() should return a UTF-8 charset instead of ISO-8859-1 as per the JSON RFC 4627

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=221_

**Comment by xbao** [comment]
Workaround:

```java
MobileApi.Builder builder = new Builder(...);
builder.setHttpRequestInitializer(new HttpRequestInitializer() {
        @Override
        public void initialize(HttpRequest request) throws IOException {
            request.setResponseInterceptor(new HttpResponseInterceptor() {
                @Override
                public void interceptResponse(HttpResponse response) throws IOException {
                    // Decode JSON as UTF-8 if no charset is specified.
                    if (response.getContentType().equals("application/json") &&
                            response.getMediaType().getCharsetParameter() == null) {
                        response.getMediaType().setCharsetParameter(Charset.forName("UTF-8"));
                    }
                }
            });
        }
    });
```
