### ISSUE TITLE
Upgrade dependency on Apache HttpClient 

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#241]
_From [paul@hammant.org](https://code.google.com/u/paul@hammant.org/) on August 13, 2013 10:05:10_

Version of google-http-java-client (e.g. 1.15.0-rc)? 1.16.0-rc Java environment (e.g. Java 6, Android 2.3, App Engine)? JDK6, Mac. Describe the problem. If I use your library with Selenium 2.34, under Maven control, I get a NoClassDefFound error in Selenium as Maven chooses your older version of Apache HttpClient.

[INFO] +- org.seleniumhq.selenium.fluent:fluent-selenium:jar:1.12:test
[INFO] |  - org.seleniumhq.selenium:selenium-java:jar:2.34.0:test
[INFO] |     +- org.seleniumhq.selenium:selenium-android-driver:jar:2.34.0:test
[INFO] |     |  - org.seleniumhq.selenium:selenium-remote-driver:jar:2.34.0:test
[INFO] |     |     +- cglib:cglib-nodep:jar:2.1_3:test
[INFO] |     |     +- org.json:json:jar:20080701:test
[INFO] |     |     - com.google.guava:guava:jar:14.0:test
[INFO] |     +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.34.0:test
[INFO] |     +- org.seleniumhq.selenium:selenium-htmlunit-driver:jar:2.34.0:test
[INFO] |     |  - net.sourceforge.htmlunit:htmlunit:jar:2.12:test
[INFO] |     |     +- xalan:xalan:jar:2.7.1:test
[INFO] |     |     |  - xalan:serializer:jar:2.7.1:test
[INFO] |     |     +- commons-collections:commons-collections:jar:3.2.1:test
[INFO] |     |     +- org.apache.commons:commons-lang3:jar:3.1:test
[INFO] |     |     +- org.apache.httpcomponents:httpmime:jar:4.2.3:test
[INFO] |     |     +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.12:test
[INFO] |     |     +- xerces:xercesImpl:jar:2.10.0:test
[INFO] |     |     |  - xml-apis:xml-apis:jar:1.4.01:test
[INFO] |     |     +- net.sourceforge.nekohtml:nekohtml:jar:1.9.18:test
[INFO] |     |     +- net.sourceforge.cssparser:cssparser:jar:0.9.9:test
[INFO] |     |     |  - org.w3c.css:sac:jar:1.3:test
[INFO] |     |     - org.eclipse.jetty:jetty-websocket:jar:8.1.9.v20130131:test
[INFO] |     |        +- org.eclipse.jetty:jetty-util:jar:8.1.9.v20130131:test
[INFO] |     |        +- org.eclipse.jetty:jetty-io:jar:8.1.9.v20130131:test
[INFO] |     |        - org.eclipse.jetty:jetty-http:jar:8.1.9.v20130131:test
[INFO] |     +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.34.0:test
[INFO] |     |  +- commons-io:commons-io:jar:2.2:test
[INFO] |     |  - org.apache.commons:commons-exec:jar:1.1:test
[INFO] |     +- org.seleniumhq.selenium:selenium-ie-driver:jar:2.34.0:test
[INFO] |     |  +- net.java.dev.jna:jna:jar:3.4.0:test
[INFO] |     |  - net.java.dev.jna:platform:jar:3.4.0:test
[INFO] |     +- org.seleniumhq.selenium:selenium-iphone-driver:jar:2.34.0:test
[INFO] |     +- org.seleniumhq.selenium:selenium-safari-driver:jar:2.34.0:test
[INFO] |     +- org.seleniumhq.selenium:selenium-support:jar:2.34.0:test
[INFO] |     |  - org.seleniumhq.selenium:selenium-api:jar:2.34.0:test
[INFO] |     - org.webbitserver:webbit:jar:0.4.14:test
[INFO] |        - io.netty:netty:jar:3.5.2.Final:test
[INFO] - com.google.http-client:google-http-client:jar:1.16.0-rc:test
[INFO]    +- com.google.code.findbugs:jsr305:jar:1.3.9:test
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.0.1:test
[INFO]    |  +- org.apache.httpcomponents:httpcore:jar:4.0.1:test
[INFO]    |  +- commons-logging:commons-logging:jar:1.1.1:test
[INFO]    |  - commons-codec:commons-codec:jar:1.3:test
[INFO]    - xpp3:xpp3:jar:1.1.4c:test How would you expect it to be fixed? Upgrade deps to 4.2.3 or thereabouts :)

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=241_

**Comment by icoloma** [comment]
HttpClient would be best repackaged and included in the jar using jarjar, or releasing a new version with the upgraded dependency. In my case, this chain is broken:

```
com.google.appengine.tools:appengine-gcs-client:0.4.4
|    +--- com.google.apis:google-api-services-storage:v1-rev15-1.19.0 -> v1-rev26-1.19.1
|    |    \--- com.google.api-client:google-api-client:1.19.1
|    |         |    +--- com.google.http-client:google-http-client:1.19.0
|    |         |    |    +--- org.apache.httpcomponents:httpclient:4.0.1
```

I cannot add Selenium on this project because it depends on Apache HTTP Client 4.3, which is incompatible with 4.0 (forcing 4.3 breaks Google HTTP Client). Releasing a version compatible with 4.3 or repackaging the dependency (using jarjar) would solve the issue. 

Please notice that this is a big issue, since low-level libraries tend to be used everywhere. In my case I cannot use Google Cloud Storage and Selenium at the same time (part of the problem is because Apache HTTP Library have included breaking changes in their API).

**Comment by Dnefedkin** [comment]
This is  @wonderfly 's quote from Jan 9, 2015

> That said, we must still adhere to compatibility with Apache HTTP Client 4.0.1 just because that's the version Android has included in their SDK.

2.5 years have passed since then. Can we review if there's a chance to finally bump up Apache HTTP Client dependency to a higher version? Ideally 4.5.x  .

**Comment by dkocher** [comment]
See also #306.

**Comment by wonderfly** [comment]
Note that older issues in this tracker were ported from code.google.com using my credentials. So everything isn't necessarily my quote. You may have noticed that every comment starts with "From xxx on yyy", indicating the original poster and date.

**Comment by chingor13** [comment]
The current dependent version is 4.5.5 although it is using deprecated API.

Track that progress in #482 and #503
