### ISSUE TITLE
Allow annotation to specify a value-converter in tandem with @Key

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#25]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on August 16, 2011 07:47:02_

External references, such as a standards document, or specification? None that I am aware of. Java environments (e.g. Java 6, Android 2.3, App Engine 1.4.3, or All)? All. Please describe the feature requested. // framework

/**
- Specifies a conversion.
  */
  interface Converter<T> {
  String toString(T obj);
  T valueOf(String value) throws ParseException;
  }

/*\* 
- Tell google-api-java-client to apply the specified conversion.
  */ 
  @Retention(RetentionPolicy.RUNTIME)
  @Target(ElementType.FIELD)
  public @interface Convert {
  Class<? extends Converter> value();
  // this is better than abusing @Key
  }

// application example

import java.awt.Color;

class ColorConverter implements Converter<Color> {
   // has parameterless default constructor

   @Override
   public String toString(Color obj) {
      // format
   }

   @Override
   public Color valueOf(String value) throws ParseException {
      // parse
   }
}

class Calendar {
 @Key("gCal:color")
 @Convert(ColorConverter.class)
 public Color color;
}

Design notes:
  The framework could inspect a Converter<T>'s method annotation to decide whether to invoke the method if the input is null.  This could spare Converter implementors from having to deal with null input.

  A framework-provided "abstract Class DefaultConverter implements Converter" could be useful.

  Parse errors should not stop reading input, but there probably needs to be a way to callback the caller of the parseAs() method.

  The use-case anticipated here doesn't need control over _collections_ (eg. @Key("entry") List<Entry> entries;) ... this case can probably be excluded from the design of the Converter.

  This converter doesn't solve more annoying issues like when the <entry/> of a calendar event feed specialises the <gd:comments/> element from the Event kind such that the <gd:feedLink/> points to a feed containing <entry/>s of the Message kind, and shouldn't try to.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=25_

**Comment by doom777** [comment]
+1. Also, I wish you guys didn't do your own serialization, and just delegated it to the existing factories like GSon, or Jackson
