### ISSUE TITLE
Allow GenericUrl.build() to be overridden

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#26]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on August 16, 2011 08:11:27_

Thanks to szieg...@cloudsherpas.com for reporting the problem!

version: 1.4.1-beta on App Engine 1.5.0.1

As an example of this issue, according to Google's documentation to retrieve the ACL Feed for a Google Docs List Entry, the link specified requires the form: https://docs.google.com/feeds/default/private/full/document&#37;3Adocument_id/acl The &#37;3A is critical as the following url (with &#37;3A replaced by a colon) returns a 404 for us: https://docs.google.com/feeds/default/private/full/document:document_id/acl That automatic decoding from &#37;3A to : happens within the internals of the GenericUrl class. 

As an attempt to work around this, I replaced the "&#37;" with a "&#37;25" with the hopes that GoogleUrl would properly escape the "&#37;25" back to a "&#37;" and all would be well: https://docs.google.com/feeds/default/private/full/document&#37;253Adocument_id/acl However, this only resulted in the GenericUrl building an unchanged, incorrect url: https://docs.google.com/feeds/default/private/full/document&#37;253Adocument_id/acl Since the methods that encode and decode within GenericUrl are final/private, there does not appear to be a way to properly construct a url to access the Google Docs ACL Feed using the class.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=26_

**Comment by fedorl** [comment]
How about making encodeParamValue member and allow it to be overriden? Or even better, add it by composition with some pluggable param encoder class and add method to plug in new encoder? 

How would you make q=%40test query with this code? 

-------------------

As a side note you guys go beyond any reason by making every single method final, and this is not only GenericUrl but the whole library and many google code in general. This is not good programming practice. 

What is the gain to prevent overriding? 1ns performance? Prevent from issues on library upgrade? 

Mention potential issues of overriding in docs and leave developers to decide.. 

You can't plan in advance for every bug or issue, and tiny issue can become a big problem with all these finals. Then "we didn't think this, we didn't think that".. 

In addition, by using final on public methods you make mocking of classes non-trivial,  requiring PowerMock or alike which can significantly increase test times.

I can understand finals in particular core methods like in java.lang.String, but here IMHO most of them are completely not justified. 

The funny thing is that "final" distribution among methods here is nearly random, e.g. getScheme is final and getPort or getFragment or getHost are not... What was the reason to make getScheme final? Who gained from this?

**Comment by dandrep** [comment]
Is there any workaround for the encoding issue? build() is encoding the '+' in a URL that I need and is breaking multiple APIs as a result. Without a workaround I have to rewrite to not use this library.

**Comment by ajaaym** [comment]
This is related to [#398](https://github.com/googleapis/google-http-java-client/issues/398) encoding + sign. We will track there closing this.
