### ISSUE TITLE
ObjectParser that uses jackson.databind.ObjectMapper

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#261]
_From [tenyoung...@gmail.com](https://code.google.com/u/112546536357481889104/) on May 10, 2014 12:12:15_

External references, such as a standards document, or specification? jackson-databind: https://github.com/FasterXML/jackson-databind

Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? All

Please describe the feature requested.
It would be nice if the Google HTTP Client's Jackson2 library contained an implementation of ObjectParser that used a Jackson2 ObjectMapper so that an HttpRequest could utilize Jackson2's data-binding functionality.

I've attached the implementation I wrote for a project. It's very simple but I imagine it'd be very convenient to have already included. I don't know about GSON or the other JSON libraries supported by Google HTTP Client but if they don't already have data-binding ObjectParsers included then I think they should, too.

**Attachment:** [ObjectMapperParser.java](http://code.google.com/p/google-http-java-client/issues/detail?id=261)

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=261_

**Comment by whoisjake** [comment]
Got bit by this one today. I am using jackson-databind in my project for things like service bus messages, logging, etc... and it worked until I hit this bug... As an end user, I figured it was all "plug-and-play" up until this point.

I'll look for a workaround for now, but this would be a great addition to the project.

**Comment by whoisjake** [comment]
Also, having access to the ObjectMapperParser.java code in the old issue would be great...
