### ISSUE TITLE
Add hooks for instrumenting request timing and getting server IP address

### ISSUE THREAD

**Issue by wachsler-google** [googleapis/google-http-java-client#277]
Add hooks to be called after a request has been sent, and as close as possible to the beginning of the response, so that the server response time can be measured independently of the time it takes to send the request body and response body.

Also add the ability to determine the IP address of the server, when possible.

**Comment by chingor13** [comment]
For part 1, we are adding OpenCensus instrumentation in #545.

For part 2, we cannot necessarily do this as the DNS resolution is handled by the transport layer. We could try an do our own DNS lookup, but this would be extra requests that is no necessarily wanted.
