### ISSUE TITLE
Increase stream copy buffer to fix slow upload

### ISSUE THREAD

**Issue by adriancretu** [googleapis/google-http-java-client#278]
Hi,
while developing an app with the Google API client library for Java I noticed that I could never pass a maximum speed of 256 KB/s for a single file upload. Meanwhile any other clients (the official google drive desktop app, the web app, and even using python client library) uploaded any single file at speeds up to 1 MB/s. This was unacceptable for large files (since famously any upload that takes longer than an hour will fail), so I dig further down the source code (and wireshark) to find out that the AbstractInputStreamContent base class is using a 4 kilobyte buffer to copy the entire source stream to destination. However this had a subtle side effect: on each write to the output the data is being flushed to the SSL socket, effectively sending a new data packet with a new SSL data record, etc.

Using such a small buffer size is bringing down the overall upload speed, because of latency issues and TCP overhead.

Overriding the writeTo(OutputStream out) method to use a larger buffer increased the upload speed by four times, and this is only because the maximum SSL record is 16 kilobytes, unfortunately.

Is there a reason for using a buffer size of 4 KB? If not, please make it 16 kilobytes since this is the maximum size of a buffer that can be sent via the SSL channel, and you can test it yourself that the upload speed will be quadrupled. I'm still uncertain how this was overlooked.

**Comment by rbeede** [comment]
I just tried using a modified InputStreamContent with a 16KiB buffer, but it didn't make a difference.  I am still seeing about 300KB / second using the Java API but over 7MB/sec if I upload from a web browser.

Any hints?

`	  
public void writeTo(OutputStream out) throws IOException {
		    final InputStream from = getInputStream(); 
		  
		    Preconditions.checkNotNull(from);
		    Preconditions.checkNotNull(out);
		    byte[] buf = new byte[16 * 1024];

		    while (true) {
		      int r = from.read(buf);
		      if (r == -1) {
		        break;
		      }
		      out.write(buf, 0, r);

		    }
		  
		    out.flush();
	  }`

**Comment by adriancretu** [comment]
Hi. First of all, you're doing read/write of a single byte, which is overkill. Since I opened this issue I had to do some nasty tweaks to gain a better throughput in Java, starting with the buffer size increase for the I/O bytes copying, but I remember i had to also create a custom file input stream to overcome some library behaviour. IIRC, writing to the output socket was done in 4K chunks, which triggered a socket flush, which triggered very high TCP latency and ultimately 256 KB/s speed. Because Java's internals also limit the SSL socket's capabilities to 16 KB / request, I hit a JVM limit there.

Since then, I switched to the Python client library, since nobody seemed to take my bug seriously and apparently nobody cares that Java uploads are 10x slower than normal.

**Comment by rbeede** [comment]
Oddly in one run where I was writing ~11MB of data that I had stored all in a byte array in Java in memory the upload went really fast (about 5 megabytes / second).

It may be possible that my network is restricting my upload speed?

Or could it be that Google is restricting my upload speed into the API as a throttle mechanism against my project key?


Subsequent runs are back down to ~350KB / sec.

**Comment by rbeede** [comment]
An example of my hacked together debugging code for this issue:

`
		//TODO see if this code really helped or not DEBUG
		System.out.println(Calendar.getInstance().getTime().toString());
		// Slurp file into memory and test that way to ensure no disk activity or nio IO api is slowing it down (was on SSD so super unlikely)
		final byte[] inmemdata = new byte[(int) Files.size(fileToUpload)];
		{
			final FileInputStream is = new FileInputStream(fileToUpload.toFile());
			final int bytesRead = is.read(inmemdata);
			is.close();
			
			if(bytesRead != Files.size(fileToUpload)) {
				throw new RuntimeException("You were correct about read not doing AT LEAST bytes");
			} else {
				System.out.println("Read " + bytesRead + " bytes of data");
			}
		}
		
		System.out.println(Calendar.getInstance().getTime().toString());
		
		
		
		final FixedInputStreamContent mediaContent = new FixedInputStreamContent(null,new ByteArrayInputStream(inmemdata));
		
		mediaContent.setLength(inmemdata.length);

`



[FixedInputStreamContent.java.txt](https://github.com/google/google-http-java-client/files/318673/FixedInputStreamContent.java.txt)

**Comment by rbeede** [comment]
It doesn't seem to stay consistent.  Sometimes I get 1.5 megabytes / second upload and other times only 300KB/sec.

Could be Google throttling my project?

**Comment by adriancretu** [comment]
I believe the endpoint server is never the same on every new upload request, hence the difference in upload speed. But the bottom line of this issue was related to some Java client library decisions which impacted overall performance; speed differences noticed without changing the code don't depend on the client library, as you experienced as well. It is very frustrating that uploading stuff via the web browser is really, really fast, but using the API in whatever language is very, very slow (relatively). Google keeps forgetting that the API is there so developers can use it for other use-cases then plain old raw file uploads (I could just use a stupid browser for this, right?), and forgets to mention limitations like these.

**Comment by adriancretu** [comment]
Also, using Wireshark is useful in determining the overall upload speed performance, even if everything goes over HTTPS. You can easily notice a bad performance by comparing the upload via the API to the upload via the web browser, and examining TCP window sizes, SSL record lengths, and such.

**Comment by rbeede** [comment]
I wonder if there is some undocumented bandwidth limit for Google Drive like they mention for Gmail here:

https://support.google.com/a/answer/1071518

**Comment by ajaaym** [comment]
4k is the default page size for most of the system. Flushing depends on so many external factor outside of this library. Given the age of this issue, I am closing this for now. If you still have performance issue please create new issue with following detail.
1. OS detail
2. hardware spec
3. sample code
4. output of jvm profiler from the machine.

**Comment by adriancretu** [comment]
Page size has nothing to do with the issue, if it's still there. The issue was that the library was flushing output data in chunks of 4k buffers, which went directly over the SSL socket, causing a bottleneck due to SSL packeting overhead. Using a 16 k buffer would have avoided the issue. I've long switched over to the Python client due to the way better performance benefits. Trying to optimise for "page size" (is that file system page size? RAM page size?) is useless if the overall "external factors" work 10x better with a slightly larger buffer size.
