### ISSUE TITLE
Get headers from request

### ISSUE THREAD

**Issue by fkautz** [googleapis/google-http-java-client#285]
Some API services require header signing. The client provides no easy way to determine what the headers will ultimately look like as they are dynamically generated on execute().

Please provide a way to view what headers will be generated if execute() were called next.

**Comment by wonderfly** [comment]
[HttpExecuteInterceptor](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/http/HttpExecuteInterceptor.html) does exactly that.

You could register an interceptor by [HttpRequest#setInterceptor()](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/http/HttpRequest.html#setInterceptor(com.google.api.client.http.HttpExecuteInterceptor)).

**Comment by fkautz** [comment]
Thanks, I'll give this a try. Closing this for now.

**Comment by fkautz** [comment]
Reopening, headers are unpopulated. Looks like the headers are generated after the intercept is called.

**Comment by ajaaym** [comment]
If you set Logging level to CONFIG for ```com.google.api.client.http.HttpTransport``` its going to log all headers along with curl request. This will help to see all the headers. I am closing this issue for now. Please reopen this issue if this doesnt help.
