### ISSUE TITLE
Returning exception on failure

### ISSUE THREAD

**Issue by fkautz** [googleapis/google-http-java-client#286]
When request.setThrowExceptionOnExecuteError(false) is set, it would be useful for the response to retain the exception that would of been thrown instead of dropping it.

e.g. 

``` java
response = request.execute();
// some failure occurred
IOException e = response.getException();
```

The use case is sometimes an error response will contain a body with additional info on the error. Retrieving this info is useful but requires exceptions to be disabled since it closes the connection and makes the body inaccessible.

**Comment by crackien** [comment]
Good

**Comment by ajaaym** [comment]
when ```request.setThrowExceptionOnExecuteError(false)``` execute() returns HttpResponse from which exception can be constructed. IOException gets thrown regardless of ```request.setThrowExceptionOnExecuteError(false)``` when happens.

Please reopen this issue if you need help with this.
