### ISSUE TITLE
SSLHandshakeException and HTTP/2

### ISSUE THREAD

**Issue by valour01** [googleapis/google-http-java-client#299]
I come across a problem when I sent a https request. 

java.security.cert.CertificateException: No subject alternative names present

I am sure that is because my ssl identity checks fail because that is just a example key for developing.

I want to know how to disable the check.

By the way, does this lib support http/2? If so, how can I send requests with different priorities.

Many thanks

**Comment by sduskis** [comment]
I'm going to close this due to staleness.  Please reopen if this is still relevant.
