### ISSUE TITLE
Request charset defaults to UTF-8, Response charset defaults to ISO_8859_1

### ISSUE THREAD

**Issue by edatkinvey** [googleapis/google-http-java-client#300]
Both the request and response objects should default to the same charsets.  This causes very hard to troubleshoot bugs with repeated requests.

from `com.google.api.client.http.HttpResponse`

```
public Charset getContentCharset() {
    return mediaType == null || mediaType.getCharsetParameter() == null
        ? Charsets.ISO_8859_1 : mediaType.getCharsetParameter();
}
```

from `com.google.api.client.http.AbstractHttpContent`

```
protected final Charset getCharset() {
    return mediaType == null || mediaType.getCharsetParameter() == null
        ? Charsets.UTF_8 : mediaType.getCharsetParameter();
}
```

Ideally both will use `Charsets.UTF_8`, as `Charsets.ISO_8859_1` only supports a subset.

**Comment by elharo** [comment]
Per the HTTP 1.1 spec, if the server does not supply a charset in the HTTP headers, then ISO-8859-1 is assumed. Thus on the request, I think we should return Charsets.8859_1 instead of Charsets.UTF_8.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
