### ISSUE TITLE
Jackson Constructors don't work properly

### ISSUE THREAD

**Issue by leeavital** [googleapis/google-http-java-client#301]
If I'm using the Jackson parser factory, I can't use `@JsonCreator` in a constructor to deserialize objects.

``` java
// BAD
public class MyClass {
    private final String key;
    public MyClass(@JsonProperty("my_key") String key) {
       this.key = key;
    }
}
```

``` java
// GOOD
public class MyClass {
   @JsonProperty("key") 
   private String key;
}
```

**Comment by ajaaym** [comment]
This library uses jackson for parsing and writing only. Its not an drop in replacement for jackson. I am closing this issue for now. If you have issue related to functionality of this library please open new issue with relevant detail.
