### ISSUE TITLE
FileDataStoreFactory method setPermissionsToOwnerOnly only supports Unix

### ISSUE THREAD

**Issue by rbeede** [googleapis/google-http-java-client#315]
com.google.api.client.util.store.FileDataStoreFactory

setPermissionsToOwnerOnly does not use newer Java 7 or 8 APIs for setting file/dir ownership and thus generates spurious warnings like "com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for everybody: "

The code only takes into account file systems as seen on Unix-like OSes that use a simple mode for the permissions.   Windows file systems have ACLs and require different API calls to modify ownership and permissions.  The latest Java APIs should be used instead which can handle both file system types.

This warning occurs for anyone using the Drive API SDK samples and causes confusion for new developers using the API.

https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java

**Comment by rbeede** [comment]
Temporary workaround:

			final java.util.logging.Logger buggyLogger = java.util.logging.Logger.getLogger(FileDataStoreFactory.class.getName());
			buggyLogger.setLevel(java.util.logging.Level.SEVERE);

**Comment by isaacbauman-2021** [comment]
> Temporary workaround:
> 
> ```
>         final java.util.logging.Logger buggyLogger = java.util.logging.Logger.getLogger(FileDataStoreFactory.class.getName());
>         buggyLogger.setLevel(java.util.logging.Level.SEVERE);
> ```

where should I put this code？
`public class Auth {

    /**
     * Define a global instance of the HTTP transport.使用new关键字来创建一个全局实例。
     */
    public static final HttpTransport HTTP_TRANSPORT = new NetHttpTransport();

    /**
     * Define a global instance of the JSON factory.
     */
    public static final JsonFactory JSON_FACTORY = new JacksonFactory();

    /**
     * This is the directory that will be used under the user's home directory where OAuth tokens will be stored.
     */
    private static final String CREDENTIALS_DIRECTORY = ".oauth-credentials";

    /**
     * Authorizes the installed application to access user's protected data.
     *
     * @param scopes              list of scopes needed to run youtube upload.
     * @param credentialDatastore name of the credential datastore to cache OAuth tokens
     */
    public static Credential authorize(List<String> scopes, String credentialDatastore) throws IOException{

        // Load client secrets.
        Reader clientSecretReader = new InputStreamReader(Auth.class.getResourceAsStream("/client_secrets.json"));
        GoogleClientSecrets clientSecrets = GoogleClientSecrets.load(JSON_FACTORY, clientSecretReader);

        // Checks that the defaults have been replaced (Default = "Enter X here").
        if (clientSecrets.getDetails().getClientId().startsWith("Enter")
                || clientSecrets.getDetails().getClientSecret().startsWith("Enter ")) {
            System.out.println(
                    "Enter Client ID and Secret from https://console.developers.google.com/project/_/apiui/credential "
                            + "into src/main/resources/client_secrets.json");
            System.exit(1);
        }

        // This creates the credentials datastore at ~/.oauth-credentials/${credentialDatastore}
        FileDataStoreFactory fileDataStoreFactory = new FileDataStoreFactory(new File(System.getProperty("user.home") + "/" + CREDENTIALS_DIRECTORY));
        DataStore<StoredCredential> datastore = fileDataStoreFactory.getDataStore(credentialDatastore);

        GoogleAuthorizationCodeFlow flow = new GoogleAuthorizationCodeFlow.Builder(
                HTTP_TRANSPORT, JSON_FACTORY, clientSecrets, scopes).setCredentialDataStore(datastore)
                .build();

        // Build the local server and bind it to port 8080
        LocalServerReceiver localReceiver = new LocalServerReceiver.Builder().setPort(8080).build();

        // Authorize.
        return new AuthorizationCodeInstalledApp(flow, localReceiver).authorize("user");
    }
}`
