### ISSUE TITLE
IllegalCharsetNameException in HttpResponse getContentCharset() if charset is malformed

### ISSUE THREAD

**Issue by Doctoror** [googleapis/google-http-java-client#323]
> Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
>        at android.os.AsyncTask$3.done(AsyncTask.java:304)
>        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
>        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>        at java.lang.Thread.run(Thread.java:818)
> Caused by java.nio.charset.IllegalCharsetNameException: %s
>        at java.nio.charset.Charset.checkCharsetName(Charset.java:197)
>        at java.nio.charset.Charset.forName(Charset.java:295)
>        at com.google.api.client.http.HttpMediaType.getCharsetParameter(HttpMediaType.java:321)
>        at com.google.api.client.http.HttpResponse.getContentCharset(HttpResponse.java:526)
>        at com.google.api.client.http.HttpResponse.parseAsString(HttpResponse.java:516)
>        at com.google.api.client.http.HttpResponseException$Builder.(HttpResponseException.java)
>        at com.google.api.client.http.HttpResponseException.(HttpResponseException.java)
>        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)

The place where this occurs is in HttpMediaType, which does not enforce valid parameter to be passed to Charset.forName()

``` java
  /**
   * Returns the specified charset or {@code null} if unset.
   */
  public Charset getCharsetParameter() {
    String value = getParameter("charset");
    return value == null ? null : Charset.forName(value);
  }
```

**Comment by ajaaym** [comment]
This is [fixed](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpMediaType.java#L322)

**Comment by ajaaym** [comment]
Sorry I misread original issue. Created PR to fix this.
