### ISSUE TITLE
Why is org.codehaus.jackson lib still used

### ISSUE THREAD

**Issue by the1plummie** [googleapis/google-http-java-client#327]
Hey guys,

Is there a reason why `org.codehaus.jackson:jackson-core-asl` is still used instead of newer `com.fasterxml.jackson.core`? I'm running into some conflicts with older/news dependencies. Would be great if we can rid of `org.codehaus.jackson.*` since it's deprecated anyway.

Thanks.

**Comment by ajaaym** [comment]
@chingor13 I just tried to remove ```google-http-client-jackson``` module and ```org.codehaus.jackson:jackson-core-asl```  It compiles and passes all test case. would this be a breaking change? Shall I send PR for this?

**Comment by sduskis** [comment]
`google-http-client-jackson` uses `org.codehaus.jackson:jackson-core-asl`.   `google-http-client-jackson2` uses `com.fasterxml.jackson.core`.

The question is: can we remove `google-http-client-jackson`?

**Comment by chingor13** [comment]
At this time, we can't as there are internal conflicts. The internal conflicts are resolvable, but will take some time.

**Comment by chingor13** [comment]
We should be able to deprecate this artifact and form a plan to remove it.

**Comment by chingor13** [comment]
Instead of reusing this issue for the process of deprecating the artifact, I opened #536.
