### ISSUE TITLE
Response content is incorrectly empty

### ISSUE THREAD

**Issue by dleshem** [googleapis/google-http-java-client#332]
I encountered a weird scenario where the remote server sends response content, but the library incorrectly returns an empty response.

I am using google-http-java-client version 1.22.0 (latest).

Here's a reference curl command that performs a simple POST to a remote server-

```
curl -X "POST" -H "Content-type: application/json" -d '{"card_holder":"test","card_number":"4222222222222","card_expiry":"12/2020","cvv":"123","amount":10000,"reference":"1471329530805","customer_ip":"23.236.62.147","currency":"AUD","capture":true}' "https://gateway.sandbox.fatzebra.com.au/v1.0/purchases" -v
```

The server returns 401 (Unauthorized) with content-type application/json, content-length 75, and the following body:

```
{"successful":false,"errors":["Incorrect Username or Token"],"result":null}
```

Here's Scala code that does the same with google-http-java-client:

```
val requestFactory = new NetHttpTransport().createRequestFactory

val httpRequest = requestFactory.buildPostRequest(
   new GenericUrl("https://gateway.sandbox.fatzebra.com.au/v1.0/purchases"),
   new ByteArrayContent("application/json",
   """{"card_holder":"test","card_number":"4222222222222","card_expiry":"12/2020","cvv":"123","amount":10000,"reference":"1471336548509","customer_ip":"23.236.62.147","currency":"AUD","capture":true}""".getBytes("UTF-8")))

httpRequest.setThrowExceptionOnExecuteError(false)

val httpResponse = httpRequest.execute()

System.out.println(s"headers: ${httpResponse.getHeaders}")
System.out.println(s"response: '${httpResponse.parseAsString}'")
```

This code prints the following:

```
headers: {content-length=[75], content-type=[application/json; charset=utf-8], date=[Tue, 16 Aug 2016 08:44:40 GMT], www-authenticate=[Basic realm=Payment API], status=[401 Unauthorized], x-request-id=[29e010bd97694b3cfc34737e11a5b34c], x-runtime=[0.010373], connection=[keep-alive], x-rack-cache=[invalidate, pass], x-backend=[sbox-priv-gateway-a]}
response: ''
```

Note that the returned response body is empty, even though the response headers are correct (e.g. content-length is 75 as it should be). Likewise, `httpResponse.getContent` returns null.

**Comment by dleshem** [comment]
By the way, directly performing the same POST request with ```java.net.URL``` works - the response body is correctly returned.

**Comment by ajaaym** [comment]
This is limitation of JDK api. It can not provide content when request is authenticating in streaming mode. Here is the detail of similar [issue](https://stackoverflow.com/questions/16748969/java-net-httpretryexception-cannot-retry-due-to-server-authentication-in-strea) Closing this issue as this is not related to this library.

**Comment by bersling** [comment]
@ajaaym I don't understand, so is there no solution to the problem or does something in the request need to be changed to fix the problem? What exactly do you mean by "when request is authenticating in streaming mode"? Can this be changed somehow?
