### ISSUE TITLE
Ability to cancel upload request for Google Drive API

### ISSUE THREAD

**Issue by wangbourne** [googleapis/google-http-java-client#343]
My question is:
How to cancel a upload request for Google Drive API? It seems that current APIs don't support this. Is there anyone could clarify about this?  if feasible, appreciate any related code snippets

This thread also referred this: https://github.com/google/google-http-java-client/issues/172..However, nobody responded.

**Comment by elharo** [comment]
This is not a question for this repo. @chingor13 please close it.
