### ISSUE TITLE
ArrayMap$Entry::hashCode -  NullPointerException for null Key and/or Value

### ISSUE THREAD

**Issue by gstor** [googleapis/google-http-java-client#344]
I am working on a Dataflow pipeline, and when I try to output a BigQuery TableRow that has a null value I get an NPE.  The stacktrace is attached.

google-http-client version: 1.21.0

I also included a link to a commit I did in a fork that has some unit tests to surface the issue, and a potential fix for the issue.  The problem is in the ArrayMap$Entry::hashCode method.  Neither the key nor the value are checked for null before calling their hashCode methods.

[ArrayMapNPE-StackTrace.txt](https://github.com/google/google-http-java-client/files/714758/ArrayMapNPE-StackTrace.txt)

[commit](https://github.com/gstor/google-http-java-client/commit/c0f1cf59999cd43ea13674244e743e91975a4a72)

[tl;dr]
I get the exception in a DoFn, where I transform an incoming object into a BigQuery TableRow, just after calling ProcessContext.output(TableRow).  Code snippet below:

```java
public void processElement(ProcessContext processContext) throws Exception {
       ...
        try {
            inputEvent = processContext.element();

            TableRow row = new TableRow();
            row.put("some_nullable_column", null);
            ...
            processContext.output(row); //--Throws NPE

        } catch(Exception e) {
            LOG.info("Exception creating TableRow: event={} stackTrace={}", inputEvent, Throwables.getStackTraceAsString(e));
            processContext.sideOutput(deadLetterTag, generateDeadLetterEvent(Constants.BQ_CREATE_ROWS, inputEvent, e));
        }
    }
```

**Comment by O1O1O1O** [comment]
What's the status of this?  I have the same problem.  Interestingly when I'm reading data from BigQuery I do get TableRows that have nulls in them...

**Comment by ajaaym** [comment]
This seems fixed [here](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/util/ArrayMap.java#L423). Closing this for now. Please reopen if this is still an issue.
