### ISSUE TITLE
Add support for Warning headers?

### ISSUE THREAD

**Issue by zolyfarkas** [googleapis/google-http-java-client#355]
It would be useful to support:

https://tools.ietf.org/html/rfc7234#section-5.5

**Comment by andrey-qlogic** [comment]
The code already supports any user defined header [public HttpHeaders set(String fieldName, Object value)](https://github.com/googleapis/google-http-java-client/blob/8e5a7bb52a90e5dc32d570ba91eb19e86af93846/google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java#L175), if it not enough we could define "Warning" header as a class field. 

@Key("Warning")
 private List<String> warning;
