### ISSUE TITLE
AndroidEnterpriseClient doesn't work with HttpClient instance obtained from HttpClients.customs method

### ISSUE THREAD

**Issue by mailniranjan** [googleapis/google-http-java-client#364]
CloseableHttpClient closeableHttpClient = HttpClients.custom()...build();
ApacheHttpTransport apacheHttpTransport = new ApacheHttpTransport(closeableHttpClient);
AndroidEnterprise enterpriseClient = new AndroidEnterprise.Builder(apacheHttpTransport, ...);
AndroidEnterprise.Products.List listProducts = enterpriseClient.products().list(enterpriseId);

The above piece of code throws the following exception.
java.lang.UnsupportedOperationException
	at org.apache.http.impl.client.InternalHttpClient.getParams(InternalHttpClient.java:210)
	at com.google.api.client.http.apache.ApacheHttpTransport.<init>(ApacheHttpTransport.java:129)

**Comment by mzogz** [comment]
Is there any traffic on this issue? It's been open about a year and it's still a problem in the core google http api using version 1.23.0.
