### ISSUE TITLE
415 Unsupported Media Type When Sending JsonHttpContent via POST Request

### ISSUE THREAD

**Issue by benjamincampbell** [googleapis/google-http-java-client#437]
Hello there,

I'm having an issue where I'm trying to send a POST request with an empty JSON object to a web API. However, even with `Content-Type=application/JSON`, I receive a 415 error from the server. This does not happen when building and sending the request with programs such as Postman, or even using the base Java `HttpURLConnection` library.

I create the Generic Url:

```
GenericUrl url = new GenericUrl("https://www.example.com/path/to/api/resource")
```

I'm creating an HttpHeaders object and building the request like so:

```
HttpHeaders headers = new HttpHeaders()
	.setContentType("application/json")
	.setAccept("application/json")
	.setAuthorization("Authentication String")

HttpRequest request = requestFactory.buildRequest("POST", url, null).setHeaders(headers)
```
(the authentication string obviously is different, but I'm using the same one that works just find in Postman)
(requestFactory is a previously-instantiated `HttpRequestFactory`)

And the Content object like so:

```
def payload = "{}"
HttpContent content = new JsonHttpContent(new JacksonFactory(), payload)
```

Finally, the mediaType, setting the Content, and executing:

```
HttpMediaType mediaType = new HttpMediaType("application/json")

content.setMediaType(mediaType)

request.setContent(content)

HttpResponse response = request.execute()
```

I'm not sure if I'm missing some small detail, like adding `;charset=UTF-8` to the `Content-Type` or `MediaType`, but I've tried both ways and neither works. Sometimes this makes the server return 500 Internal Server Errors. I do feel like the error of my ways lies somewhere in setting the `Content-Type`; I do notice in the logging that two `Content-Type`s are displayed, but both are set to `application/json`.

The thing that gets me is that the request is just fine with Postman or with the Java `HttpURLConnection` based library, so I'm clearly missing something specific to this library. I can also send GET requests with no issue.

Thank you for your time, please let me know if any other information is needed; I believe I've included all of the relevant code

**Comment by benjamincampbell** [comment]
I should add that using this library, prior to this request, I'm able to send a `POST` request that retrieves the authentication string with no issues; it sends a `UrlEncodedContent` object, not JSON, but I've had no weird `Content-Type` issues with that.

I also am able to send `GET` requests to a different resource in the API and retrieve data with no issues using this library; it seems to be something specific to how I'm sending `JsonHttpContent` to the resource.

**Comment by benjamincampbell** [comment]
I also realized I should be calling `response.disconnect()` after I retrieve the needed data from the response, thinking perhaps the prior Authentication request which was expecting `application/x-www-form-urlencoded;charset=UTF-8` was still open, but this did not fix the issue.

**Comment by ajaaym** [comment]
This seems resolved. If this needs attention please reopen issue with following detail, successful request from postman, request from client library, response from server from postman and client library.
