### ISSUE TITLE
Refactor parseElementInternal(...) in XML.java

### ISSUE THREAD

**Issue by geri-m** [googleapis/google-http-java-client#490]
In order to improve readability and extendability the method ```parseElementInternal(...)``` in ```XML.java``` needs some refactoring. This enables us to add additional feature later. 

Before heading for a code change, more unit tests should be implemented.

**Comment by elharo** [comment]
Is this still in progress or done?

**Comment by geri-m** [comment]
@elharo I was unable to complete this ticket, as the complexity of the code given was too high. happy to close the ticket and mark the refactoring as unresolved.
