### ISSUE TITLE
ApacheHttpTransport uses deprecated APIs and cannot be used with recommended HttpClient APIs

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-http-java-client#503]
`ApacheHttpTransport` class uses many deprecated APIs from Apache HTTP Client. There are around 75 deprecation warnings in that class alone.

Moreover, it is now impossible to use the `ApacheHttpTransport` with a recommended implementation of Apache HttpClient. For instance, the following doesn't work:

```
import org.apache.http.impl.client.HttpClients;

public void testDefaultClient() {
  new ApacheHttpTransport(HttpClients.createDefault());
}
```

The above fails with the following error:

```
java.lang.UnsupportedOperationException
	at org.apache.http.impl.client.InternalHttpClient.getParams(InternalHttpClient.java:211)
	at com.google.api.client.http.apache.ApacheHttpTransport.<init>(ApacheHttpTransport.java:127)
	at com.google.api.client.http.apache.ApacheHttpTransportTest.testDefaultClient(ApacheHttpTransportTest.java:98)
```

This is because new `HttpClient` implementations do not expose their `HttpParams` and `ConnectionManager` (both these getters have been deprecated, and most default implementations now throw errors).

Realistically one can only use `ApacheHttpTransport` with `DefaultHttpClient`, which itself is a deprecated API now.

**Comment by hiranya911** [comment]
I can provide a pull request to migrate this implementation out of the deprecated APIs, and make it work with recommended implementations of `HttpClient`. Is that something that can be beneficial to this project? However, I don't know what impact this change may have on Android developers. I've only tested my changes on server-side Java.

Other possible solutions include:
1. Implementing a `NewApacheHttpTransport` using none of the deprecated APIs from Apache HTTP client.
2. Exposing the `ApacheHttpRequest` and `ApacheHttpResponse` APIs so that developers can implement their own transport using them.

**Comment by chingor13** [comment]
After #543 is merged, we should be able to fix the Apache HttpClient implementation to use non-deprecated classes. Any help would be greatly appreciated.

**Comment by hiranya911** [comment]
Thanks @chingor13. I can probably find some time over the coming weeks to implement this.
