### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#513]
There's no CI server so it's no surprise the tests are broken right now. This should be fixed ASAP. 

Looks like the issue may be that the hook isn't installed to connect the CI server to the PRs.

**Comment by chingor13** [comment]
Kokoro is configured as CI for master and all pull requests. If you are an organization member (googleapis), then tests run automatically, otherwise someone needs to add the `kokoro: force-run` label and tests will run.

**Comment by elharo** [comment]
So how do we make this run for everybody, not just organization members?

**Comment by chingor13** [comment]
We'd have to file a feature request against Kokoro - the options are:
* no automatic runs
* automatic runs for organization members and/or repository collaborators

**Comment by chingor13** [comment]
Our team explicitly migrated all client libraries off of the third-party CI services to Kokoro.
