### ISSUE TITLE
Create a BOM for google-http-java-client

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-http-java-client#516]
google-http-java-client needs a BOM, as per https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-15.md .

Of note: a parent pom.xml isn't appropriate to use as a BOM, because it specifies versions of dependencies in its `dependencyManagement` section, whereas a BOM should **only** contain the modules within this repo (google-http-client-*). If you create a BOM without touching the parent, there would be duplication of the repo's module versions; I recommend having the parent import the BOM it its `dependencyManagement` section so that you don't have such duplication. You can check the BOM & parent pom.xml in google-cloud-java as a reference.

I would recommend `google-http-client-bom` as the name of the BOM artifact.

cc @elharo

**Comment by chingor13** [comment]
All the artifacts are `google-http-client-XX` -- should we make it `google-http-client-bom`?

Also, should `google-http-client-parent` be included and/or include the new bom in its dependencies?

**Comment by garrettjonesgoogle** [comment]
Oops that's what I should have said for the name (I'll update the description).

The parent shouldn't be in the BOM.

The parent should import the BOM in its dependencyManagement section; it shouldn't be a dependency (that provides nothing to you at all).
