### ISSUE TITLE
Run javadoc tests

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-http-java-client#524]
We're currently skipping javadoc tests when running CI.

We may also need to set up a conditional profile for Java 8 for the Xdoclint option.

**Comment by geri-m** [comment]
I think ```<doclint>none</doclint>``` is what we are looking for (https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#doclint). I'll give it a shot.

**Comment by igorbernstein2** [comment]
I didn't know about `<doclint>`.  That's way better than my profile hack
