### ISSUE TITLE
HttpBackOffUnsuccessfulResponseHandler#handleResponse, removing final?

### ISSUE THREAD

**Issue by sebfz1** [googleapis/google-http-java-client#549]
Would it be possible to remove the final modifier from `HttpBackOffUnsuccessfulResponseHandler#handleResponse` [1] so it lets a chance to log or trigger something? (without having to rewrite it)
`HttpBackOffIOExceptionHandler` [2] does not have the final modifier for instance.

[1] https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpBackOffUnsuccessfulResponseHandler.java#L139
[2] https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpBackOffIOExceptionHandler.java#L108

#### Environment details

- OS: Linux Ubuntu
- Java version: 1.8.0_181
- google-http-java-client version: 1.27.0

**Comment by chingor13** [comment]
Can you describe the type of logging you want to add? Perhaps, we could instrument this for everyone.

Removing final wouldn't do much unless we also change all the members to protected.

**Comment by sebfz1** [comment]
I've an SDK that communicates with my system. The client don't have to handle the `HttpRequest` directly, but still can he define a timeout+retry strategy (simple, exponential, etc). So I supply the base object (`HttpRetryStrategy`) in which 2 events can be fired (one by `HBOURH#handleResponse`, one by `HBOIOEH#handleIOException`), up to him to log or do whatever he wants

I don't need to have members changed to protected (it actually forces me to call super `return super.handleResponse(request, response, supportsRetry);` preventing any misbehavior)

I've something like this, works great so far:  

```
request.setReadTimeout(this.httpRetryStrategy.getReadTimeout());
request.setNumberOfRetries(this.httpRetryStrategy.getNumberOfRetries());

/** one BackOff per request, but same is used for both unsuccessful-response and io-exception */
final BackOff backOff = this.httpRetryStrategy.newBackOff();

if (backOff != null) {
	request.setUnsuccessfulResponseHandler(new HttpBackOffUnsuccessfulResponseHandler(backOff) {

		@Override
		public boolean handleResponse(HttpRequest request, HttpResponse response, boolean supportsRetry) throws IOException {

			httpRetryStrategy.onFailure(request, response, supportsRetry);
			return super.handleResponse(request, response, supportsRetry);
		}
	};

	request.setIOExceptionHandler(new HttpBackOffIOExceptionHandler(backOff) {

		@Override
		public boolean handleIOException(HttpRequest request, boolean supportsRetry) throws IOException {

			httpRetryStrategy.onException(request, supportsRetry);
			return super.handleIOException(request, supportsRetry);
		}
	});
}
```
