### ISSUE TITLE
Setting keep-alive on NetHttpTransport

### ISSUE THREAD

**Issue by nwbirnie** [googleapis/google-http-java-client#551]
The comments at the top of [NetHttpTransport](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/http/javanet/NetHttpTransport) suggest this class can be used for setting keep-alive. However, I don't see anywhere to do that. Is this comment perhaps out of date, and if so, what is the preferred method for setting keep alive?

Thanks!

**Comment by chingor13** [comment]
If you are using the `NetHttpTransport` adapter, you set the keep alive settings either via:
* system properties (`http.keepAlive` and `http.maxConnections`) which will configure this globally
* [http request/response headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) which can be done on a per request basis (`Connection: keep-alive`)

The above choice is really up to you.

To set headers on a request:
```java
HttpHeaders headers = request.getHeaders();
headers.set("Connection", "keep-alive");
request.setHeaders(headers);
```
