### ISSUE TITLE
com.google.android:android is for cupcake?

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#581]
This is at HEAD: 

google-http-java-client/blob/master/google-http-client/pom.xml pulls in 

```   
<dependency>
      <groupId>com.google.android</groupId>
      <artifactId>android</artifactId>
      <version>1.5_r4</version>
      <scope>provided</scope>
    </dependency>
```

This is very old and pulls in many other 10+ year old dependencies with some linkage problems . 

Can this be upgraded to a more recent version?

**Comment by elharo** [comment]
The readme says "Android 4.0 (Ice Cream Sandwich) (or higher)" which suggests we can upgrade this several versions. 

Even Ice Cream Sandwich is now unsupported: https://www.extremetech.com/mobile/282002-google-finally-ends-support-for-android-4-0-ice-cream-sandwich

I'm not sure exactly which version of the android artifact we need.

**Comment by elharo** [comment]
Ping me for a pointer to internal discussion. This artifact seems to be deprecated now. Can we just get rid of it?

**Comment by elharo** [comment]
Robolectric builds the android.jar of every version and pushes it to Maven Central: https://search.maven.org/search?q=g:org.robolectric%20AND%20a:android-all&core=gav

This may work better than the old one we are using.

**Comment by elharo** [comment]
There are something like 11 uses of this artifact:

https://mvnrepository.com/artifact/com.google.http-client/google-http-client-android/usages

2 of those are in this repo.
Of the remaining 9, only one has been updated in the last year.

**Comment by elharo** [comment]
also relevant: why does the main artifact seem to depend on this? Could we cut that dependency short  of completely deleting this?

**Comment by chingor13** [comment]
Looks like the android dependency was removed in #591
