### ISSUE TITLE
Maven 2.1.0 and 2.2.0 produce incorrect GPG signatures and checksums respectively

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#583]
Warning during mvn test:

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Maven 2.1.0 and 2.2.0 produce incorrect GPG signatures and checksums respectively.

**Comment by elharo** [comment]
OK, looks like the enforcer plugin wants 3.5.4 and I have 3.5.0, but then when does the message say 2.1.0 and 2.2.0?

**Comment by chingor13** [comment]
I don't think there's anything actionable here. This message comes from maven tools.
