### ISSUE TITLE
Fix backwards compatibility in google-api-client

### ISSUE THREAD

**Issue by sduskis** [googleapis/google-http-java-client#606]
#543 broke backwards compatibility.  (see [here](https://github.com/googleapis/google-cloud-java/issues/4579) for the ripple effect).

#543 broke apart `google-api-client` into two packages, but removed some public classes.  That type of change requires a major semver change.

In the short term, we need to add a dependency in `google-http-client` to `google-http-client-apache` to preserve backwards compatibility until we have a major new release of `google-http-client`.

**Comment by sduskis** [comment]
First attempt by adding the dependency:

[ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='com.google.http-client:google-http-client-apache:2.0.1-SNAPSHOT'}' and 'Vertex{label='com.google.http-client:google-http-client:1.28.1-SNAPSHOT'}' introduces to cycle in the graph com.google.http-client:google-http-client:1.28.1-SNAPSHOT --> com.google.http-client:google-http-client-apache:2.0.1-SNAPSHOT --> com.google.http-client:google-http-client:1.28.1-SNAPSHOT @

**Comment by elharo** [comment]
It looks like there's also a 2.0.0 version of google-http-client-apache. Could we simply revert #543 for 1.29.0?

**Comment by sduskis** [comment]
I think that we'd have to:

1. maintain an empty(ish) jar for the new artifact and move the .java files and dependencies back to the original artifact. 
2. release 1.29.0
3. revert the change and release a new 2.*
