### ISSUE TITLE
google-http-client-apache-v2 - resolving via m2 central?

### ISSUE THREAD

**Issue by vegaasen** [googleapis/google-http-java-client#683]
### Problem details

This is rather not an issue with any of the libraries itself, but a request for how to use `google-http-client-apache-v2`. Right now, the library is not available in maven central - or atleast I cannot find it. Is it supposed to be published there?

Also, whilst specifying version 2.x of the `google-http-client-apache`-client, the content of the `jar`-file is rather emtpy - i.e, it does not contain any java classes at all. Something happened with the release?

The reason we'd like to use the `v2` of the httpClient is due to Firebase which does not support Apache HttpClient v 4.4+ with the included version of `google-http-client-apache`. In order to get this working, we need to use `v2` of this library. However, when this library is not quite that available it becomes a bit harder.

Right now, we've included the sourcecode from this repo (`google-http-client-apache-v2`) in our repo, which is not..well..awesome :-P

#### Environment details

- OS: OS X
- Java version: 12
- google-http-java-client version: "google-http-client-apache-v2"

#### Steps to reproduce

N/A

#### Stacktrace

```
N/A
```

#### External references such as API reference guides used

N/A

#### Any additional information below

Viewing contents of: 

https://search.maven.org/artifact/com.google.http-client/google-http-client-apache/2.1.1/jar

results in 👇:
```
 vegaasen@Vegards-MacBook-Pro ~/Downloads/webstep-download  $ jar -tvf google-http-client-apache-2.1.1.jar 
   724 Thu Apr 25 19:22:36 CEST 2019 META-INF/MANIFEST.MF
     0 Thu Apr 25 19:22:36 CEST 2019 META-INF/
     0 Thu Apr 25 19:22:36 CEST 2019 META-INF/maven/
     0 Thu Apr 25 19:22:36 CEST 2019 META-INF/maven/com.google.http-client/
     0 Thu Apr 25 19:22:36 CEST 2019 META-INF/maven/com.google.http-client/google-http-client-apache/
  3932 Thu Apr 25 19:19:34 CEST 2019 META-INF/maven/com.google.http-client/google-http-client-apache/pom.xml
   113 Thu Apr 25 19:22:34 CEST 2019 META-INF/maven/com.google.http-client/google-http-client-apache/pom.properties
```

See the main section (problem details).

Hope you guys can help us!

Kind regards,
Vegard

**Comment by chingor13** [comment]
Apologies, the google-http-client-apache-v2 artifact has not yet been published and is included in the 1.30.0 release.

**Comment by vegaasen** [comment]
Ah, alright I see 👍 ! When is the version 1.30.0 to be expected being released, you recon?

**Comment by vegaasen** [comment]
Closing this issue for now, as version 1.30.0 will be released soon and mitigates our httpComponents/client issue 👍

**Comment by chingor13** [comment]
[1.30.0](https://github.com/googleapis/google-http-java-client/releases/tag/v1.30.0) was released today and should be available on maven central
