### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [googleapis/google-http-java-client#725]
Hi
The following lines have cryptographic API misuses. <br> File name => google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java: Line number => 131: API name => Signature:Operation on object of type java.security.Signature object not completed. Expected call to initSign, initVerify<BR> File name => google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java: Line number => 166: API name => Signature:<BR> File name => google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java: Line number => 126: API name => Signature:First parameter (with value "SHA1withRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java: Line number => 147: API name => Signature:<BR>

**Comment by chingor13** [comment]
These line numbers look off and there is not enough information. The information provided also looks incorrect as the usage appears correct.
