### ISSUE TITLE
google-http-client-apache-v2 1.30.2 does not have ApacheHttpTransport.newDefaultHttpClientBuilder

### ISSUE THREAD

**Issue by chanseokoh** [googleapis/google-http-java-client#735]
The method was introduced in #713 to fix #578. Did it get removed? Why?

I've been eagerly waiting for the 1.30.2 release, hoping it would unblock https://github.com/GoogleContainerTools/jib/issues/1434

**Comment by chingor13** [comment]
I backported #717 into a 1.30.2 release. #713 was adding to the API so it was going to be added to 1.31.0. I was hoping to get a few more fixes in before 1.31.0

**Comment by chanseokoh** [comment]
Ah, that makes sense. Thanks. Knowing that #713 will make into 1.31.0, this is no longer an issue. I'll close it.
