### ISSUE TITLE
mvn verify errors; mostly clirr

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#770]
[WARNING] 6003: com.google.api.client.http.HttpRequest: Value of compile-time constant USER_AGENT_SUFFIX has been changed
[WARNING] 6003: com.google.api.client.http.HttpRequest: Value of compile-time constant VERSION has been changed
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebSignature$Header: Return type of method 'public com.google.api.client.json.GenericJson clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebSignature$Header: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.json.GenericJson
[ERROR] 7002: com.google.api.client.json.webtoken.JsonWebSignature$Header: Method 'public java.lang.String getX509Certificate()' has been removed
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebSignature$Header: Return type of method 'public com.google.api.client.json.GenericJson set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebSignature$Header: Return type of method 'public com.google.api.client.util.GenericData set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.json.GenericJson
[ERROR] 7002: com.google.api.client.json.webtoken.JsonWebSignature$Header: Method 'public com.google.api.client.json.webtoken.JsonWebSignature$Header setX509Certificate(java.lang.String)' has been removed
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebToken$Header: Return type of method 'public com.google.api.client.util.GenericData clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebToken$Header: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebToken$Payload: Return type of method 'public com.google.api.client.util.GenericData clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.json.webtoken.JsonWebToken$Payload: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.util.GenericData

**Comment by elharo** [comment]
some of these look really weird; like something chnged and changed back; and I can't find them in the relevant class

**Comment by jaredreiss39** [comment]
Vancouver
