### ISSUE TITLE
Import order warnings

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#771]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/apache/SSLSocketFactoryExtension.java:27: Wrong order for 'org.apache.http.conn.ssl.SSLSocketFactory' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/apache/HttpExtensionMethod.java:17: Wrong order for 'org.apache.http.client.methods.HttpEntityEnclosingRequestBase' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpResponse.java:20: Wrong order for 'org.apache.http.Header' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java:31: Wrong order for 'org.apache.http.HttpHost' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpRequest.java:21: Wrong order for 'org.apache.http.HttpEntityEnclosingRequest' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/apache/ContentEntity.java:22: Wrong order for 'org.apache.http.entity.AbstractHttpEntity' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java:31: Wrong order for 'java.util.concurrent.atomic.AtomicLong' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java:31: Wrong order for 'java.io.IOException' import. [ImportOrder]
[WARN] /tmpfs/src/github/google-http-java-client/google-http-client/src/main/java/com/google/api/client/testing/http/apache/MockHttpClient.java:20: Wrong order for 'org.apache.http.ConnectionReuseStrategy' import. [ImportOrder]

**Comment by elharo** [comment]
A lot of these look OK to me and IntelliJ with Google formatter doesn't change them. Possibly we need to update the Maven style rules.

**Comment by meredithslota** [comment]
Fixed by https://github.com/googleapis/google-http-java-client/pull/786, I believe. Closing. Please reopen if this isn't yet fixed.
