### ISSUE TITLE
Remove deprecated ApacheHttpTransport

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#779]
Only even still present for pre-Gingerbread android, which we haven't supported for years. This might moot #778

**Comment by chingor13** [comment]
We only deprecated this in May 2019, so we cannot remove this until November 2020 according to our stated policy.

**Comment by elharo** [comment]
November 2020 has passed. Let's take it out.

**Comment by stephaniewang526** [comment]
This is the preferred resolution for b/172238231.
