### ISSUE TITLE
SBT assembly merge conflicts with google-http-client as a source

### ISSUE THREAD

**Issue by turboT4** [googleapis/google-http-java-client#811]
So far the code itself works like a charm, but when assembly time comes the following is prompt in the logs, both belonging to the same library.

```
[error] /Users/sample/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/http-client/google-http-client-apache/2.0.0/google-http-client-apache-2.0.0.jar:com/google/api/client/http/apache/ApacheHttpRequest.class
[error] /Users/sample/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/http-client/google-http-client/1.29.1/google-http-client-1.29.1.jar:com/google/api/client/http/apache/ApacheHttpRequest.class
[error] deduplicate: different file contents found in the following:
[error] /Users/sample/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/http-client/google-http-client-apache/2.0.0/google-http-client-apache-2.0.0.jar:com/google/api/client/http/apache/ApacheHttpTransport.class
[error] /Users/sample/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/http-client/google-http-client/1.29.1/google-http-client-1.29.1.jar:com/google/api/client/http/apache/ApacheHttpTransport.class
[error] deduplicate: different file contents found in the following:
[error] /Users/sample/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/http-client/google-http-client-apache/2.0.0/google-http-client-apache-2.0.0.jar:com/google/api/client/http/apache/ContentEntity.class
[error] /Users/sample/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/http-client/google-http-client/1.29.1/google-http-client-1.29.1.jar:com/google/api/client/http/apache/ContentEntity.class
```

And my current Google libraries are the following ones.

    val googleCloudV    = "1.75.0"
    val googleHadoopV   = "1.9.4-hadoop3"    

    val cloudStorage = "com.google.cloud"            % "google-cloud-storage" % googleCloudV
    val cloudHadoop  = "com.google.cloud.bigdataoss" % "gcs-connector"        % googleHadoopV

First time I find a conflict of this kind and don't really know which strategy to take as I suspect its an issue with mismatching library versions. Also tried to exclude one of the versions, either -apache or the standard one and still the same issue.

**Comment by chingor13** [comment]
Can you figure out which dependency is pulling in `google-http-client-apache` 2.0.0? That particular version was a mistake to release without changing the java package name for this exact reason. If you are controlling that dependency, you'll instead want `google-http-client-apache-v2` as a dependency.

**Comment by turboT4** [comment]
@chingor13 the one which makes `sbt assembly` to crash is the following one, as the `hadoop` dependency was already there and the project used to compile flawlessly.

`val cloudStorage = "com.google.cloud"            % "google-cloud-storage" % googleCloudV`

No matter what I exclude, it always prompts the same error. I've tried everything, including removing all the `google` dependencies from the `repo1.maven.org` directory in `.coursier` cache.

**Comment by burkedavison** [comment]
Closing this issue due to age.
