### ISSUE TITLE
Docs should link to  release notes

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#862]
We lost these in the doc migration.

https://github.com/googleapis/google-http-java-client/releases

Ideally we should have human curated notes, not just a list of commits. 

E.g. something like https://cloud.google.com/eclipse/docs/release-notes

**Comment by chingor13** [comment]
With conventional commits, these commits should combine to make coherent releases. Additional, we are working on infrastructure to pull these release notes into the cloud doc site as well.
