### ISSUE TITLE
Option to use "Location:" header value verbatim for redirection

### ISSUE THREAD

**Issue by chanseokoh** [googleapis/google-http-java-client#864]
**Is your feature request related to a problem? Please describe.**
There have been problems with interacting Azure Container Registry, OpenShift Container Registry, and Red Hat Quay, where these servers return a redirect location (the `Location:` header value) but they fail to honor a redirect URL if it doesn't match the original URL value char-by-char.

(FYI, the ACR issue has been taken care of by [setting `setNormalizeUri(false)`](https://github.com/googleapis/google-http-java-client/pull/804/files#diff-c70a5908a02499325cafe08dff35f283R43) on Apache HttpClient. However, [Microsoft should fix their servers](https://github.com/googleapis/google-http-java-client/issues/795#issuecomment-526569413) eventually.)

Examples:
- Microsoft: https://github.com/googleapis/google-http-java-client/issues/795#issuecomment-526679306
- Red Hat: https://github.com/GoogleContainerTools/jib/issues/2106#issuecomment-547593721
- Red Hat: https://groups.google.com/d/msg/quay-sig/2y7tMP0h0g0/IMUQyDDpAgAJ
- Red Hat: https://github.com/GoogleContainerTools/jib/issues/1986#issuecomment-537623394

**Describe the solution you'd like**
As described in https://github.com/googleapis/google-http-java-client/issues/795#issuecomment-526679306, an option to take the `Location:` URL value and use it verbatim, without ever modifying any character.

**Describe alternatives you've considered**
Wait for Red Hat to fix their servers, which they said [won't likely happen for a very long time](https://groups.google.com/forum/#!topic/quay-sig/2y7tMP0h0g0).

**Additional context**
Fixing this may first require enhancing `GenericUrl` to disable encoding and decoding (but I am not sure).

**Comment by iocanel** [comment]
@chanseokoh: Getting the `Location:` and using it as is, doesn't seem very hard to implement, does this also require additional work in `httpcomponents-client` side?

**Comment by chanseokoh** [comment]
I quickly hacked `GenericUrl` and tried a call to see if the server side can get the URL as-is, and it gets it as-is. This library sets `setNormalizeUri(false)` on the Apache library, so perhaps the Apache library does not mangle with it either.

Implenenting this feature may not be terribly difficult, but it may need cascading changes to `GenericUrl`, `UrlEncodedParser` and some others, I don't know. And since the API is GA and public, I see such changes cannot be taken lightly.

**Comment by iocanel** [comment]
@chanseokoh: I've started working on a pull request (modifying GenericUrl and UrlEncodedParser). 
Please let me know if I should continue, or if you are going to pick this up.

**Comment by chanseokoh** [comment]
Wonderful! You can continue on this, thanks a ton. And note that I believe this library has an automatic redirection handling (the user does not have to parse `Location:` and make another redirect call), so make sure that is taken care of too. Or perhaps, you just take care of that execution path only, without making this URL-pass-through general for any calls. I am not sure.
