### ISSUE TITLE
HttpResponse: Cannot change charset

### ISSUE THREAD

**Issue by myin142** [googleapis/google-http-java-client#877]
### Environment details

OS: Linux 5.1
Java Version: 8
google-http-client version: 1.33.0

#### Steps to reproduce

I have no problems getting it to run. I followed the basic steps to create a requests:

```java
HTTP_TRANSPORT.createRequestFactory()
    .buildPostRequest()
    .execute()
    .parseAs(SomeClass.class);
```

Do not know if it is a bug or if I did something wrong. But the problem is when it tries to parse it, it always uses the default Charset ISO-8859-1. Even if I set the charset in the request/content. Tried:

```java
httpContent.setMediaType(new HttpMediaType("text/xml").setCharsetParameter(StandardCharsets.UTF_8));
```
```java
request.getHeaders().setContentType("text/xml; charset=UTF-8");
```

Inside the HttpContent the charset is indeed UTF-8. But after executing the request, the response is always ISO-8859-1.
My current workaround is to use the parser directly and set the charset manually.

**Comment by chanseokoh** [comment]
I believe the `Content-Type` of a request specifies to the content type of the request (and the `Content-Type` of a response specifies the type of the response, of course). It doesn't mean "I want the server to get this type of content" but rather "the content (if present) of my request is this type." The `Content-Type` of a request and that of a response are separate and completely unrelated, and one cannot imply/dictate the outcome of the other. I think the server is merely sending what it think should; the server serves the content you requested and it believes the type of the content being sent has ISO-8859-1 charset. If you believe that the type of the content sent from the server is actually not ISO-8859-1, perhaps the server should be fixed to correctly identify the type and send it (unless this library has a bug where the server did send the correct charset but failed to populate and set it correctly in Java).

And one header related to what you are possibly thinking of is `Accept-Charset`, but reading [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset), in practice I think `Accept-Charset:` is largely ignored and often not a practical solution (for good reasons). (Note there's `Accep:t` too.)

**Comment by myin142** [comment]
Yeah, you might be right. The server is pretty old and maybe they did not think about setting the right charset. I can probably close this issue. Thanks for the clarification.
