### ISSUE TITLE
Versions newer than 1.32.0 report wrong version in User-Agent on Android

### ISSUE THREAD

**Issue by abelthefirst** [googleapis/google-http-java-client#892]
I'm using 1.33.0, but the version reported is 0.0.

`User-Agent: Google-HTTP-Java-Client/0.0 (gzip)`

The reason is the implementation of the `BaseDexClassLoader.getPackage(String name)` - https://android.googlesource.com/platform/libcore/+/refs/heads/master/dalvik/src/main/java/dalvik/system/BaseDexClassLoader.java#305

**Comment by elharo** [comment]
did you mean newer than 1.32.0? If it's older, upgrading is  a fix.

**Comment by abelthefirst** [comment]
> did you mean newer than 1.32.0? If it's older, upgrading is a fix.

You're right, I fixed the title, sorry for the confusion.

**Comment by elharo** [comment]
https://github.com/googleapis/google-api-java-client/pull/1425/files might be related

@abelthefirst Can you reproduce this using only google-http-java-client? Any chance this is coming from some other library (where we made recent changes around this header)

**Comment by elharo** [comment]
https://github.com/googleapis/google-http-java-client/pull/806 is probably the culprit

**Comment by elharo** [comment]
suspect we can change

```
private static String getVersion() {
...
    if (version == null) {
```

to 

```
private static String getVersion() {
    String version = HttpRequest.class.getPackage().getImplementationVersion();
    // in a non-packaged environment (local), there's no implementation version to read
    if (version == null || "0.0".equals(version)) {
```

but I need a test case first.

**Comment by elharo** [comment]
This may also be failing in GAX
