### ISSUE TITLE
google-http-client-android 1.31+ Posix crash

### ISSUE THREAD

**Issue by adriancretu** [googleapis/google-http-java-client#906]
> com.google.api.client.util.store.FileDataStoreFactory.setPermissionsToOwnerOnly

uses `PosixFilePermission`
This class was added only in Android API 26. Running on lower API devices results in:

> Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/nio/file/attribute/PosixFilePermission;
com.google.api.client.util.store.FileDataStoreFactory.setPermissionsToOwnerOnly

Crash happens when trying to store OAuth credentials and doing something trivial like

> new FileDataStoreFactory(filesDir)

Maybe since the package releases as "Android-compatible" this should be documented?

**Comment by elharo** [comment]
This is the code. It probably needs to catch `LinkageError` too and possibly use reflection:

```
  static void setPermissionsToOwnerOnly(File file) throws IOException {
    Set permissions = new HashSet<PosixFilePermission>();
    permissions.add(PosixFilePermission.OWNER_READ);
    permissions.add(PosixFilePermission.OWNER_WRITE);
    permissions.add(PosixFilePermission.OWNER_EXECUTE);
    try {
      Files.setPosixFilePermissions(Paths.get(file.getAbsolutePath()), permissions);
    } catch (UnsupportedOperationException exception) {
      LOGGER.warning("Unable to set permissions for " + file
          + ", because you are running on a non-POSIX file system.");
    } catch (SecurityException exception) {
      // ignored
    } catch (IllegalArgumentException exception) {
      // ignored
    }
  }
```
