### ISSUE TITLE
Docs: googleplus-simple-cmdline-sample is 404 Not Found

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-http-java-client#922]
https://googleapis.github.io/google-http-java-client/json.html has a link to 404 Not Found.

https://github.com/googleapis/google-http-java-client/tree/master/samples/googleplus-simple-cmdline-sample

![image](https://user-images.githubusercontent.com/28604/71184781-417e3000-2248-11ea-84d3-79b1f86fa8a7.png)

**Comment by fmooreg** [comment]
The Google+ API was shut down on 2019-03-07, as per https://developers.google.com/+/api-shutdown, so the documentation should be updated with a different example.
